name: Golang API Config test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Test config module
      run: cd ./backend/api-docker/api/config &&
           go mod init github.com/Timotej979/Dragonhack24-BunchLunch/backend/api-docker/api/config &&
           go test